[package]
name = "rdis"
version = "0.1.0"
authors = ["TA Thanh Dinh <tathanhdinh@gmail.com>"]

[dependencies]
# quicli = "*"
failure = "*"
structopt = "*"
capstone = { git = "https://github.com/capstone-rust/capstone-rs.git" }